name: untitled
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  mongo_dart: ^0.9.3  # MongoDB driver for Dart
  qr_flutter: ^4.1.0  # QR code generation
  mobile_scanner: ^3.5.6  # Modern barcode and QR scanning
  intl: ^0.19.0  # For date/time formatting
  path_provider: ^2.1.2  # File system access
  shared_preferences: ^2.2.2  # Local storage
  provider: ^6.1.1  # State management
  pdf: ^3.10.7  # PDF generation for reports
  printing: ^5.11.1  # PDF printing support
  excel: ^4.0.2  # Excel file generation
  crypto: ^3.0.3  # For generating unique codes
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/img/
    - assets/fonts/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
